# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdEHmuZxd5wCrc4r-DJgtoc8Sh-mUbpU
"""

import streamlit as st

st.title("Hello, World!")
st.write("This is a simple Streamlit app deployed from GitHub!")